name: socmint_frontend
description: SOCMINT Platform Frontend
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  theme_provider: ^0.6.0
  fl_chart: ^1.0.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.1
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.8.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.12
  intl: ^0.19.0
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  intl_translation: ^0.18.1
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo/
    - assets/images/logo/logo_primary.png
    - assets/images/logo/logo_white.png
    - assets/images/logo/logo_black.png
    - assets/images/logo/favicon.png
  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
        - asset: assets/fonts/Dubai-Medium.ttf
          weight: 600
        - asset: assets/fonts/Dubai-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700

  # Localization
